
---
flags:
  WeakRef: useWeakRefs
  FinalizationRegistry: useWeakRefs
  class-fields-private: usePrivateClassFields
  class-static-fields-public: usePublicStaticClassFields
  class-static-fields-private: usePrivateStaticClassFields
  Intl.DateTimeFormat-dayPeriod: useIntlDateTimeFormatDayPeriod
  SharedArrayBuffer: useSharedArrayBuffer
  Atomics: useSharedArrayBuffer
  Array.prototype.at: useAtMethod
  TypedArray.prototype.at: useAtMethod
  String.prototype.at: useAtMethod
skip:
  features:
    - Atomics.waitAsync
    # https://bugs.webkit.org/show_bug.cgi?id=174931
    - regexp-lookbehind
    - legacy-regexp

    - class-methods-private
    - class-static-methods-private
    - cleanupSome
    - host-gc-required
    # https://bugs.webkit.org/show_bug.cgi?id=202475
    - regexp-match-indices
    - top-level-await
    - Intl.ListFormat
  paths:
    # test262 bot is using Catalina's ICU 64, upgrading to Big Sur is required
    # https://bugs.webkit.org/show_bug.cgi?id=218844
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts
    - test/intl402/DateTimeFormat/prototype/formatRange/date-same-returns-single-date.js
  files:
    # test262 bot needs to be upgraded to Big Sur.
    # https://bugs.webkit.org/show_bug.cgi?id=218844
    - test/language/identifiers/part-unicode-13.0.0-escaped.js
    - test/language/identifiers/part-unicode-13.0.0.js
    - test/language/identifiers/start-unicode-13.0.0-escaped.js
    - test/language/identifiers/start-unicode-13.0.0.js

    # requires ICU 65 (https://unicode-org.atlassian.net/browse/ICU-20654)
    - test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js
    - test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-auto.js

    # Do not work with ICU 64, and work with ICU 66 or later.
    - test/intl402/NumberFormat/prototype/format/numbering-systems.js

    # Catalina bot is using older SDK which is shipping < 64 ICU.
    - test/intl402/NumberFormat/constructor-compactDisplay-compact.js
    - test/intl402/NumberFormat/constructor-compactDisplay-no-compact.js
    - test/intl402/NumberFormat/constructor-notation.js
    - test/intl402/NumberFormat/constructor-signDisplay.js
    - test/intl402/NumberFormat/constructor-unit.js
    - test/intl402/NumberFormat/constructor-unitDisplay.js
    - test/intl402/NumberFormat/currencyDisplay-unit.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-de-DE.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-en-US.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-de-DE.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-en-US.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-rounding.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/unit-de-DE.js
    - test/intl402/NumberFormat/prototype/format/unit-en-US.js
    - test/intl402/NumberFormat/prototype/format/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/unit-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/unit-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/units.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/percent-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit.js
    - test/intl402/NumberFormat/prototype/resolvedOptions/compactDisplay.js
    - test/intl402/NumberFormat/style-unit.js

    # New ICU (66~) raises a different failure
    - test/intl402/Locale/constructor-non-iana-canon.js
