
---
flags:
  WeakRef: useWeakRefs
  FinalizationRegistry: useWeakRefs
  class-fields-private: usePrivateClassFields
  class-static-fields-public: usePublicStaticClassFields
  class-static-fields-private: usePrivateStaticClassFields
  Intl.DateTimeFormat-dayPeriod: useIntlDateTimeFormatDayPeriod
  SharedArrayBuffer: useSharedArrayBuffer
  Atomics: useSharedArrayBuffer
  Array.prototype.at: useAtMethod
  TypedArray.prototype.at: useAtMethod
  String.prototype.at: useAtMethod
skip:
  features:
    - Atomics.waitAsync
    # https://bugs.webkit.org/show_bug.cgi?id=174931
    - regexp-lookbehind
    - legacy-regexp

    - class-methods-private
    - class-static-methods-private
    - cleanupSome
    - host-gc-required
    # https://bugs.webkit.org/show_bug.cgi?id=202475
    - regexp-match-indices
    - top-level-await
  paths:
  files:
    # Slightly different formatting. We should update test262 side.
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/en-US.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/fractionalSecondDigits.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-rounding.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/unit-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-zh-TW.js

    # New ICU (66~) raises a different failure
    - test/intl402/Locale/constructor-non-iana-canon.js
